theme = "material_palenight"

[editor]
true-color = true
auto-format = true

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true

[keys.normal]
"_" = "goto_line_start"
"$" = "goto_line_end"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.select]
"_" = "goto_line_start"
"$" = "goto_line_end"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
