[[languages]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[languages]]
name = "rust"
auto-format = true

[[languages]]
name = "json"
config = { "provideFormatter" = true, "json" = { "keepLines" = { "enable" = true } } }
